version: '3.9'

services:

  django:
    container_name: django
    build:
      context: requirements/django
      dockerfile: Dockerfile
    env_file: 
    - .env
    networks:
      - ts-network
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - "postgresSQL"
    volumes:
      - django:/django-files
    restart: on-failure # always # Restart containers on system boot and in case of failures
    pull_policy: never # Do not pull images from Docker hub, etc

  postgresSQL:
    container_name : postgresSQL
    image: postgres:17beta1-bullseye
    env_file:
      - .env
    networks:
     - ts-network
    expose:
      - "5432"
    restart: on-failure #always
    volumes:
      - database:/var/lib/postgresql/data/

networks:
  ts-network:
    driver: bridge

volumes:
  django:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../M_django-data'
  database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../M_database'


