version: '3.9'

services:

  django:
    container_name: django
    build:
      context: requirements/django
      dockerfile: Dockerfile
    env_file: 
    - .env
    networks:
      - ts-network
    expose:
      - "8000" #only exposed internally
    # ports:
    #   - "8000:8000"
    depends_on:
      - "postgresSQL"
    volumes:
      - static_volume:/home/app/web/staticfiles
    # restart: on-failure # always # Restart containers on system boot and in case of failures

  postgresSQL:
    container_name : postgresSQL
    image: postgres:17beta1-bullseye
    env_file:
      - .env
    networks:
     - ts-network
    expose:
      - "5432"
    restart: on-failure #always
    volumes:
      - database:/var/lib/postgresql/data/

  nginx:
    container_name: nginx
    build:
     context: requirements/nginx
     dockerfile: Dockerfile
    env_file: 
      - .env 
    networks:
       - ts-network
    ports:
      - "8080:80"   # For HTTPS
    restart: on-failure #always
    depends_on:
      - django
    volumes:
      - static_volume:/home/app/web/staticfiles
      #- dist:/var/www/html

    # frontend:
  #   build:
  #     context: requirements/frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   restart: always
  #   volumes:
  #     - dist:/app/dist
  #     - ./frontend:/app

networks:
  ts-network:
    driver: bridge

volumes:
  static_volume:
    # driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: '../M_django-data'
  database:
    # driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: '../M_database'
  # dist:


