version: '3.9'

services:

  django:
    container_name: django
    build:
      context: containers/django
      dockerfile: Dockerfile
    env_file: 
    - .env
    networks:
      - ts-network
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - "postgressql"
    volumes:
      - django:/django-files
    # restart: on-failure # always # Restart containers on system boot and in case of failures

  postgressql:
    container_name : postgressql
    build:
      context: containers/postgressql
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
     - ts-network
    expose:
      - "5432"
    restart: on-failure #always
    volumes:
      - database:/var/lib/postgresql/data/

  nginx:
    container_name: nginx
    build:
     context: containers/nginx
     dockerfile: Dockerfile
    env_file: 
      - .env 
    networks:
       - ts-network
    ports:
      - "8443:443"   # For HTTPS
    restart: on-failure #always
    depends_on:
      - django
    volumes:
      - dist:/var/www/html/dist/

    # frontend:
  #   build:
  #     context: containers/frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   restart: always
  #   volumes:
  #     - dist:/app/dist
  #     - ./frontend:/app

networks:
  ts-network:
    driver: bridge

volumes:
  django:
    driver: local
    # driver_opts:
    #   device: '../M_django-data'
    #   type: 'none'
    #   o: 'bind'
  database:
    driver: local
    # driver_opts:
    #   device: '../M_database'
    #   type: 'none'
    #   o: 'bind'
  dist:
    driver: local


