version: '3'

services:

  django:
    container_name: django
    networks:
      - ts-network
    volumes:
      - django:/django-files
    build:
      context: requirements/django
      dockerfile: Dockerfile
    env_file: 
    - .env
    restart: on-failure
      # depends_on:
      #   - "mariadb"
    ports:
      - "8000:8000"

  # mariadb:
  #   container_name: mariadb
  #   networks:
  #     - ts-network
  #   volumes:
  #     - mariadb:/var/lib/mysql
  #   build:
  #     context: requirements/mariadb
  #     dockerfile: Dockerfile
  #   env_file: 
  #   - .env
  #   restart: on-failure
  #   expose:
  #     - "3306"

  # nginx:
  #   container_name: nginx
  #   networks:
  #     - ts-network
  #   volumes:
  #     - django:/var/www/wordpress
  #   build:
  #     context: requirements/nginx
  #     dockerfile: Dockerfile
  #   env_file: 
  #   - .env
  #   restart: on-failure
  #   ports:
  #     - "443:443"

networks:
  ts-network:
    driver: bridge

volumes:
  django:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../django-data'


